# name: My First Workflow
# on: push
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello
#         run: echo "Hello Sarthak"

# name: Fixed Workflow
# on: push
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello
#         run: echo "Hello Sarthak"
#       - name: Show Date
#         run: date
#       - name: Show Files
#         run: ls

name: Checkout Example
on: push
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
      - name: Show Files
        run: ls
      - name: Show Current Folder
        run: pwd