# This is a basic workflow to help you get started with Actions
# name: My First Workflow
# on: push
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello
#         run: echo "Hello Sarthak"

# This is a basic workflow, and is meant to help you get started with Actions. You can delete this file, and start from scratch, or you can edit it to fit your needs. The workflow will run on every push to the repository.
# name: Fixed Workflow
# on: push
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello
#         run: echo "Hello Sarthak"
#       - name: Show Date
#         run: date
#       - name: Show Files
#         run: ls

# This workflow will checkout the repository, show the files in the repository, and show the current folder. You can modify this workflow to fit your needs.
# name: Checkout Example
# on: push
# jobs:
#   checkout-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download Repository
#         uses: actions/checkout@v4
#       - name: Show Files
#         run: ls
#       - name: Show Current Folder
#         run: pwd


# This workflow will install a programming language of your choice. You can modify this workflow to fit your needs.
# name: Node Example
# on: push
# jobs:
#   node-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
#       - name: Install Node.js
#         uses: actions/setup-node@v4 #install node.js
#         with:
#           node-version: 18 #specify the version of node.js you want to install
#       - name: Check Node.js Version
#         run: node -v
#       - name: Check npm Version
#         run: npm -v

# This workflow will run the start script defined in your package.json file. You can modify this workflow to fit your needs.
# name: Node CI
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#       - name: Install Dependencies
#         run: npm install #npm init -y to create package.json file and npm install to install dependencies
#       - name: Run Application
#         run: npm start

# This workflow will run the start script defined in your package.json file and also cache the npm dependencies to speed up the workflow. You can modify this workflow to fit your needs.
# name: Node CI
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: 'npm'
#       - name: Install Dependencies
#         run: npm install #npm install is used to install the dependencies defined in the package-lock.json file
#       - name: Run Application
#         run: npm start

# 
name: Multiple Jobs Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Print Build Message
        run: echo "This is the build job"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test Message
        run: echo "This is the test job"